fieldLayouts:
  5e669df5-a269-43ef-b73d-0976229bab2d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-03T07:57:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 148b8211-befa-484f-8332-30d2df5db612
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T08:01:44+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: 7f8d0742-9dae-459c-ad69-040ad268b306
            userCondition: null
        name: tag01
        uid: 5c688092-96e7-44cf-b2d8-7f8eb0fc71ef
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-03T08:01:44+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: d641ac38-ccf3-4713-8fa0-e928bb2a0d9a
            userCondition: null
        name: tag02
        uid: 21132d58-c784-47c7-9d2b-078850db102c
        userCondition: null
handle: entrytags
name: entryTags
