color: null
fieldLayouts:
  21df1f02-b0b6-410e-ba11-ceb9ecd7fdaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-21T01:55:08+00:00'
            elementCondition: null
            fieldUid: a3afbe90-6f07-4821-985b-e6891d041f96 # entryImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1ad0bd0-4253-4ff2-8e88-179d56567290
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-21T01:53:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e60e566c-bd74-4f63-8177-1d9ae55bdab8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-21T01:55:08+00:00'
            elementCondition: null
            fieldUid: 4a32fc6d-95d3-4754-a5ba-6949b01d01c7 # entryUrl
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81c8f1a8-3d68-47fb-9464-22942fba3fca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-21T01:55:08+00:00'
            elementCondition: null
            fieldUid: ea976903-2cc8-487d-aff1-61f99c873b37 # entryDiscription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fe64a71-c417-493d-b44d-4121b229d092
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T07:54:19+00:00'
            elementCondition: null
            fieldUid: b26b33e8-52a3-4f96-8998-b500d9d6886e # entryTag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a74591f5-2547-4340-82dc-4f9303667fba
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: 48c5d32f-7811-47d9-91ef-4c1312b17fed
        userCondition: null
handle: entryContent
hasTitleField: true
icon: null
name: entryContent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
