defaultPlacement: end
fieldLayouts:
  18f4a3ef-0a45-4f9e-a6b8-732ae3104e7a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-21T01:37:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e0e9d431-35d6-4c83-b763-d37a3ad9f1dc
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: 7db28952-367b-43d0-9273-bcb2603ab621
        userCondition: null
handle: designcategory
name: designCategory
siteSettings:
  0982ccc7-8b77-445e-ac6b-ffbff5fc138b: # WebDesignClip
    hasUrls: true
    template: designcategory/_category.twig
    uriFormat: 'designcategory/{slug}'
structure:
  maxLevels: null
  uid: 31ba5e2b-af44-49f4-80bc-2a9a4e54f819
