defaultPlacement: end
fieldLayouts:
  c23ae351-9802-45f1-bf49-fede1fdc8545:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-21T01:38:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ad62b7fb-36da-4385-812f-0faa3ba37a94
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: aca1e228-b9ea-4e0a-b377-7007b840bee9
        userCondition: null
handle: fashionCategory
name: fashionCategory
siteSettings:
  0982ccc7-8b77-445e-ac6b-ffbff5fc138b: # WebDesignClip
    hasUrls: true
    template: fashion-category/_category.twig
    uriFormat: 'fashion-category/{slug}'
structure:
  maxLevels: null
  uid: 03072091-cfa5-43f6-ad06-120774c2df53
