defaultPlacement: end
fieldLayouts:
  32a963ad-f9f0-475c-af85-d98f558e7c83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-21T01:39:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: cd115c8d-638e-4621-947c-846c84cfbd4f
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: caa6f4ef-d72b-497f-99c5-22e530ad1d8b
        userCondition: null
handle: othercategory
name: otherCategory
siteSettings:
  0982ccc7-8b77-445e-ac6b-ffbff5fc138b: # WebDesignClip
    hasUrls: true
    template: othercategory/_category.twig
    uriFormat: 'othercategory/{slug}'
structure:
  maxLevels: null
  uid: 52c31720-5d38-4aab-bf54-3339ebb7babc
