altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  996a82e2-e946-468d-80b7-150c8848bdf0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-20T08:53:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d41a161e-0721-4b0d-8760-fe9fbf9149b0
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: a1445757-4bac-4a4f-b8e2-b9663dd3e588
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
