columnSuffix: null
handle: entryTag
instructions: null
name: entryTag
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - design
        -
          - value
          - designCategory
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - fashion
        -
          - value
          - fashionCategory
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - office
        -
          - value
          - officeCategory
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - other
        -
          - value
          - otherCategory
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
