columnSuffix: null
handle: entryImage
instructions: null
name: entryImage
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:a8933d7d-7e49-4cb9-b272-82dd7b6a49c2' # Uploads
  defaultUploadLocationSubpath: '/sectionImage/{slug}'
  maintainHierarchy: false
  maxRelations: null
  minRelations: 0
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a8933d7d-7e49-4cb9-b272-82dd7b6a49c2' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:a8933d7d-7e49-4cb9-b272-82dd7b6a49c2' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
