dateModified: 1739843607
email:
  fromEmail: kaori@cdgrph.com
  fromName: WebDesignClip
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    87a01ad4-7251-4ef2-bd7c-46f111fff5f5: WebDesignClip # WebDesignClip
    0982ccc7-8b77-445e-ac6b-ffbff5fc138b: WebDesignClip # WebDesignClip
system:
  edition: solo
  live: true
  name: WebDesignClip
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
